### ISSUE TITLE
source build_webrtc.sh

### ISSUE THREAD

**Issue by Frank-HeFei** [pristineio/webrtc-build-scripts#103]
Error: Command '/usr/bin/python -u src/sync_chromium.py --target-revision 7779e7d30f6b9b0041e769ceffed59bdcfa85d4d' returned non-zero exit status 2 in /Users/frankhe/Documents/webrtc-build-scripts/ios/webrtc
Hook '/usr/bin/python -u src/sync_chromium.py --target-revision 7779e7d30f6b9b0041e769ceffed59bdcfa85d4d' took 42.18 secs
[0mRunning ninja
ninja: Entering directory `out_ios_x86_64/Release-iphonesimulator/'
ninja: fatal: chdir to 'out_ios_x86_64/Release-iphonesimulator/' - No such file or directory
Running libtool
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/frankhe/Documents/webrtc-build-scripts/ios/webrtc/src/out_ios_x86_64/Release-iphonesimulator/*.a (No such file or directory)
Running strip
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open file: /Users/frankhe/Documents/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-9350-ios-x86_64-Release.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/frankhe/Documents/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-9350-ios-armeabi_v7a-Release.a (No such file or directory)

**Comment by ArikYa** [comment]
It seems to be a general WebRTC problem, please look here: https://groups.google.com/forum/#!topic/discuss-webrtc/Dt-GRIlLVe4
