### ISSUE TITLE
Push to maven working?

### ISSUE THREAD

**Issue by oliverhausler** [pristineio/webrtc-build-scripts#113]
Is your push to maven working? I don't see any new versions there since 17-Jun-2015 (version 9456).

**Comment by kolencherry** [comment]
@oliverhausler Currently, the push to maven is not working. We're working to bring up up. Unfortunately, our lovely Jenkins instance decided to go on strike.

**Comment by ArikYa** [comment]
pushing to Maven central is working again, the latest can be found at: https://search.maven.org/#artifactdetails|io.pristine|libjingle|9694|pom

**Comment by MichaelSiddi** [comment]
Hi, 
is the push to maven not working again? The last available version seems to be is **11139** (30 dec 2015)
