### ISSUE TITLE
Correction to Windows build instructions

### ISSUE THREAD

**Issue by eguendelman** [pristineio/webrtc-build-scripts#115]
I finally managed to build using the Vagrant image on a Windows host, and there are two caveats that people need to be aware of:

1. When I did a `git clone` on this repository, I ended up getting the shell scripts with Windows-style line endings (\r\n).  I guess this may not happen for everyone (depends on how git was set up), but to be safe you should run `dos2unix` (assuming you have cygwin) on the scripts in the `android` folder prior to doing anything.

2. By default, the virtual machine is set up with a `/vagrant` folder which is synced/shared with the host machine.  The problem is that the Windows host (or at least Windows 7 in my case) doesn't seem to deal with very long path names that the chromium checkout procedure attempts to create.  So I ended up creating a folder in the VM (not synced with host) and building there.  i.e. after `vagrant ssh`, I did:

```bash
mkdir mybuild
cd mybuild
cp /vagrant/build.sh .
source ./build.sh
get_webrtc
build_apprtc
```

Additional note:

- make sure you have ~ 24 GB of free space in the disk where the virtual machine will be created.  At least this is what I ended up using after building both Release and Debug targets.  You can open VirtualBox and configure it to create VMs in a drive with enough space, prior to starting this procedure.

**Comment by ArikYa** [comment]
@eguendelman can you test the new branch and see if it address your end-of-line issues? You should do a clean clone using the fix branch (git clone -b fix_windows_eol git@github.com:pristineio/webrtc-build-scripts.git).
I tested this partially on a Windows VM, and it seems to work

**Comment by eguendelman** [comment]
Okay, I've verified that I get the scripts with correct UNIX-style line endings on that branch.  Thanks for the fix.

**Comment by ArikYa** [comment]
@eguendelman thank you for testing my fix. I also added to the instructions information about the possible problems and your workaround.
