### ISSUE TITLE
Build fails as of r9701: libjingle_examples.gyp has been moved

### ISSUE THREAD

**Issue by ciparis** [pristineio/webrtc-build-scripts#119]
https://chromium.googlesource.com/external/webrtc/+/a8736448970fedd82f051c6b2cc89185b755ddf3
 --> "move the libjingle_examples.gyp file into webrtc directory."

**Comment by thebehera** [comment]
We know of the issue and will eventually fix it. Unfortunately we do not have the bandwith at the moment. Pull requests with fixes are always welcome!

**Comment by ciparis** [comment]
I'll submit a PR if I can get through the next error(s). Stuck at:
gyp: webrtc/libjingle.gyp not found
(lib jingle.gyp is in /talk and webrtc/libjingle) -- haven't figured out what is referencing that yet.

**Comment by divyamML** [comment]
libjingle_examples.gyp references it

**Comment by divyamML** [comment]
any updates ?

**Comment by ArikYa** [comment]
I just pushed a fix for this issue.
