### ISSUE TITLE
Ninja build issue, wrong dependency, no build progress.

### ISSUE THREAD

**Issue by McPo** [pristineio/webrtc-build-scripts#121]
Ran into issues regarding ninja.

When I ran build_apprtc it failed to find ninja. Prompting me to install it with 

    apt-get install ninja

This however installs the ninja security program not the build system, which lead to the following screen.

    log: ninja version 0.1.3 initializing
    log: magic group: gid=0 (root)
    log: entering main loop
    log: generating initial pid array..
    log: now monitoring process activity
    log: ignored signal: 28

Instead had to run.

    apt-get install ninja-build

It appears the install_dependencies doesn't install ninja_build. Im on Ubuntu 12.04.5 LTS, not sure whats different from my configuration.

**Comment by ArikYa** [comment]
ninja is part of depot_tools, so it should be there. If you were able to run gclient, I don't see any reason for ninja to not be there. What was exactly the order of the commands you issued?

**Comment by McPo** [comment]
mkdir webrtc
cd webrtc
git clone https://github.com/pristineio/webrtc-build-scripts.git
cd webrtc-build-scripts
. ./android/build.sh
install_dependencies
get_webrtc
build_apprtc

However the whole thing was a bit of hack and slash from me.
I may have copied an old version of gclient into the VM I was using.

Probably safe to close this issue then. At least the issue has been documented if people run into it in the future.
