### ISSUE TITLE
Is it possible to build Android on Amazon Linux (CentOS)?

### ISSUE THREAD

**Issue by soulfly** [pristineio/webrtc-build-scripts#123]
Is it possible to build Android on Amazon Linux (CentOS)?

**Comment by ArikYa** [comment]
The official WebRTC build instructions states Ubuntu and Debian as the supported platform. We use Ubuntu, but you are welcome to test

**Comment by soulfly** [comment]
I tried the origin guide http://www.webrtc.org/native-code/android bit no luck, had an issue with 

    ninja -C out/Debug

get an error with clang and paths

     ../../chromium/src/third_party/modp_b64/modp_b64.h:136:10: fatal error: 'string' file not found
     #include <string>
              ^
     1 error generated.

**Comment by ArikYa** [comment]
Sorry it didn't work. These are just helpful wrapper scripts, that are based on the original build system. If it doesn't work on any specific platform, there isn't much we can do
