### ISSUE TITLE
iPhone 6/6Plus problem

### ISSUE THREAD

**Issue by JiggyTank** [pristineio/webrtc-build-scripts#139]
Hi,

I am using the latest libwebrtc.a from apprtc iOS demo. I am able to connect with firefox from my iPhone 5 but remote video is coming blank when I try to connect iPhone 6 /6+ with firefox. Remote video is blank on both side. ICE State is never going to 2.

Firefox SDP:
v=0

o=mozilla...THIS_IS_SDPARTA-41.0.2 2117551108990887526 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 F1:5E:87:2F:5A:00:0F:AF:7B:43:4B:1C:C0:A8:77:2D:E8:C9:49:AD:F1:1B:C6:63:B1:D1:D3:49:56:2F:CC:8E

a=group:BUNDLE audio video

a=ice-options:trickle

a=msid-semantic:WMS *

m=audio 60784 RTP/SAVPF 111

c=IN IP4 54.85.82.48

a=candidate:0 1 UDP 2130444543 192.168.1.3 56147 typ host

a=candidate:4 1 UDP 2130116863 169.254.168.17 51378 typ host

a=candidate:1 1 UDP 1694244863 182.XXX.XX.XXX 56147 typ srflx raddr 192.168.1.3 rport 56147

a=candidate:3 1 UDP 100409343 54.85.82.48 60784 typ relay raddr 54.85.82.48 rport 60784

a=sendrecv

a=end-of-candidates

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=ice-pwd:2bf661ce791ebe840b5a37baa1f017f0

a=ice-ufrag:6b8079d7

a=mid:audio

a=msid:{0dda78c9-000d-634d-ab11-52373eaf4488} {7d05d53e-2e43-4f4c-8bcf-74ead00891f2}

a=rtcp-mux

a=rtpmap:111 opus/48000/2

a=setup:active

a=ssrc:3764241474 cname:{bc7daddb-e3e3-2746-96d2-b1f7ca1b731e}

m=video 60784 RTP/SAVPF 100

c=IN IP4 54.85.82.48

a=sendrecv

a=fmtp:100 max-fs=12288;max-fr=60

a=ice-pwd:2bf661ce791ebe840b5a37baa1f017f0

a=ice-ufrag:6b8079d7

a=mid:video

a=msid:{0dda78c9-000d-634d-ab11-52373eaf4488} {0917e03b-9b4a-d94f-86fb-c400a238b3d1}

a=rtcp-fb:100 nack

a=rtcp-fb:100 nack pli

a=rtcp-fb:100 ccm fir

a=rtcp-mux

a=rtpmap:100 VP8/90000

a=setup:active

a=ssrc:1465213087 cname:{bc7daddb-e3e3-2746-96d2-b1f7ca1b731e}

iPhone 6+ SDP

v=0

o=- 7890469074306643928 2 IN IP4 127.0.0.1

s=-

t=0 0

a=sendrecv

a=group:BUNDLE audio video

a=msid-semantic:WMS ARDAMS

m=audio 9 RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 127 126

c=IN IP4 0.0.0.0

a=candidate:211156821 1 udp 2122260223 192.168.1.5 62943 typ host generation 0

a=candidate:211156821 2 udp 2122260222 192.168.1.5 64260 typ host generation 0

a=candidate:1108738981 1 tcp 1518280447 192.168.1.5 51793 typ host tcptype passive generation 0

a=candidate:1108738981 2 tcp 1518280446 192.168.1.5 51794 typ host tcptype passive generation 0

a=candidate:2781507712 2 udp 1686052606 182.XXX.XX.XXX 64260 typ srflx raddr 192.168.1.5 rport 64260 generation 0

a=candidate:2781507712 1 udp 1686052607 182.XXX.XX.XXX 62943 typ srflx raddr 192.168.1.5 rport 62943 generation 0

a=candidate:2913867230 2 udp 41885694 54.85.82.48 56744 typ relay raddr 182.XXX.XX.XXX rport 64260 generation 0

a=candidate:2913867230 1 udp 41885695 54.85.82.48 60576 typ relay raddr 182.XXX.XX.XXX rport 62943 generation 0

a=sendrecv

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=fingerprint:sha-256 74:D0:3B:73:78:0D:69:55:EE:F5:CD:A2:CB:C9:07:F0:3C:AA:FF:BA:61:BE:6D:CF:F6:FF:5F:16:C5:9D:33:F4

a=fmtp:111 PROFILE=0;LEVEL=0;packetization-mode=0;level-asymmetry-allowed=0;parameter-add=1;usedtx=0;stereo=0;useinbandfec=1;cbr=0

a=ice-pwd:fcEK4BjEuh5kx5xLMieNBIp7

a=ice-ufrag:Yyj2dlxa/6mHaZVV

a=maxptime:60

a=mid:audio

a=rtcp:9 IN IP4 0.0.0.0

a=rtcp-mux

a=rtpmap:111 opus/48000/2

a=rtpmap:103 ISAC/16000/1

a=rtpmap:104 ISAC/32000/1

a=rtpmap:9 G722/8000/1

a=rtpmap:102 ILBC/8000/1

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:106 CN/32000/1

a=rtpmap:105 CN/16000/1

a=rtpmap:13 CN/8000/1

a=rtpmap:127 red/8000/1

a=rtpmap:126 telephone-event/8000/1

a=setup:actpass

a=ssrc:1570274850 cname:Xq8StS69/JBeswmB

a=ssrc:1570274850 msid:ARDAMS ARDAMSa0

a=ssrc:1570274850 mslabel:ARDAMS

a=ssrc:1570274850 label:ARDAMSa0

m=video 9 RTP/SAVPF 100 116 117 96

c=IN IP4 0.0.0.0

a=candidate:211156821 1 udp 2122260223 192.168.1.5 55561 typ host generation 0

a=candidate:211156821 2 udp 2122260222 192.168.1.5 54334 typ host generation 0

a=candidate:1108738981 1 tcp 1518280447 192.168.1.5 51795 typ host tcptype passive generation 0

a=candidate:1108738981 2 tcp 1518280446 192.168.1.5 51796 typ host tcptype passive generation 0

a=candidate:2781507712 1 udp 1686052607 182.XXX.XX.XXX 55561 typ srflx raddr 192.168.1.5 rport 55561 generation 0

a=candidate:2781507712 2 udp 1686052606 182.XXX.XX.XXX 54334 typ srflx raddr 192.168.1.5 rport 54334 generation 0

a=candidate:2913867230 1 udp 41885695 54.85.82.48 51931 typ relay raddr 182.XXX.XX.XXX rport 55561 generation 0

a=candidate:2913867230 2 udp 41885694 54.85.82.48 51629 typ relay raddr 182.XXX.XX.XXX rport 54334 generation 0

a=sendrecv

a=extmap:2 urn:ietf:params:rtp-hdrext:toffset

a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:4 urn:3gpp:video-orientation

a=fingerprint:sha-256 74:D0:3B:73:78:0D:69:55:EE:F5:CD:A2:CB:C9:07:F0:3C:AA:FF:BA:61:BE:6D:CF:F6:FF:5F:16:C5:9D:33:F4

a=ice-pwd:fcEK4BjEuh5kx5xLMieNBIp7

a=ice-ufrag:Yyj2dlxa/6mHaZVV

a=mid:video

a=rtcp:9 IN IP4 0.0.0.0

a=rtcp-fb:100 ccm fir

a=rtcp-fb:100 nack

a=rtcp-fb:100 nack pli

a=rtcp-mux

a=rtpmap:100 VP8/90000

a=rtpmap:116 red/90000

a=rtpmap:117 ulpfec/90000

a=rtpmap:96 rtx/90000

a=setup:actpass

a=ssrc:409675870 cname:Xq8StS69/JBeswmB

a=ssrc:409675870 msid:ARDAMS ARDAMSv0

a=ssrc:409675870 mslabel:ARDAMS

a=ssrc:409675870 label:ARDAMSv0

a=ssrc:3882721020 cname:Xq8StS69/JBeswmB

a=ssrc:3882721020 msid:ARDAMS ARDAMSv0

a=ssrc:3882721020 mslabel:ARDAMS

a=ssrc:3882721020 label:ARDAMSv0

iPhone5/6/6+ is working fine with Chrome but not with firefox.

Please help as I am trying to solve this issue from many days but not able to.

Thanking you in advance,
Jiggy

**Comment by kolencherry** [comment]
Please note that we do not provide support for webrtc-related issues; we only provide support for these build scripts. I would recommend reaching out to the [webrtc google group](https://groups.google.com/forum/#!forum/discuss-webrtc).

**Comment by JiggyTank** [comment]
Thanks Kolencherry. I will do that.
