### ISSUE TITLE
get_webrtc does not seem to invoke "git pull" in libwebrtc src

### ISSUE THREAD

**Issue by ibc** [pristineio/webrtc-build-scripts#147]
Should `get_webrtc` produce a `git pull` of the libwebrtc source? I don't see that (testing for iOS).

**Comment by kolencherry** [comment]
`get_webrtc` calls `update2Revision`, which configures gclient and calls `sync`. `sync` executes a `gclient sync`, which updates/clones the associated webrtc repositories. The deps for the underlying webrtc library use a multiple VCSes. `gclient` performs the appropriate commands (behind the scenes) to keep them up to date.

**Comment by ibc** [comment]
Thanks.
