### ISSUE TITLE
iOS build - cannot create universal lib

### ISSUE THREAD

**Issue by sarsonj** [pristineio/webrtc-build-scripts#154]
Hi,

I updated script yesterday and since then, the build failed on creating universal lib. The platform depended lib are created correctly, but in the last step the lipo command failed:

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/sarsonj/Documents/work/git/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11244-ios-armeabi_v7a-Release.a /Users/sarsonj/Documents/work/git/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11244-ios-arm64_v8a-Release.a /Users/sarsonj/Documents/work/git/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11244-ios-x86-Release.a /Users/sarsonj/Documents/work/git/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11244-ios-x86_64-Release.a (No such file or directory)

All files mentioned there exists (so can't open input file doesn't mean, that the file doesn't exists).

**Comment by matthias62** [comment]
Hello,

I have the same problem. Same error message at the end of the compilation.

@sarsonj : Could you please help me with that: How can I build the latest release. I cloned the repo in December and got a build 11080. Now I wanted to actualize it with the current changes of the repo. I pulled the new scripts. Then I called source ios/build.sh and dance. Unfortunately I get libs with the same old release number 11080 and not with the current version number of the repo. Do I miss a step when fetching the changes of the repo?

**Comment by zhihanhe** [comment]
so do I,All the file is smaller than before

**Comment by zhihanhe** [comment]
Is someone fixed this issue?

**Comment by atsakiridis** [comment]
Hi @sarsonj @zhihanhe, I fixed that by changing:

```
lipo -create "/Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-armeabi_v7a-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-arm64_v8a-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-x86-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-x86_64-Debug.a" -output "/Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-arm-intel-Debug.a"
```

To: 

```
lipo -create -output /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-arm-intel-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-armeabi_v7a-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-arm64_v8a-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-x86-Debug.a /Users/antonis/Documents/telestax/code/webrtc-build-scripts/ios/webrtc/libjingle_peerconnection_builds/libWebRTC-11366-ios-x86_64-Debug.a
```

Seems that quoting the separate builds per architecture doesn't work for me (maybe because I'm in OSX?). Anyway with the second invocation where the multiple args go in the end, it works fine.

**Comment by zhihanhe** [comment]
thank you @atsakiridis, you help me a lot! Thang you very much!!!!

**Comment by kolencherry** [comment]
PR in-review. Thanks for the contribution @atsakiridis.

**Comment by lboquan** [comment]
Still have this problem after fixing the script depend on atsakiridis' suggestion.
