### ISSUE TITLE
Local video not rendered

### ISSUE THREAD

**Issue by lboquan** [pristineio/webrtc-build-scripts#168]
I have an iOS app that depends on this library. Everything works fine before libWebRTC-12081-arm-intel-Release. When I rebuild and update library to this release, something's wrong with my app. It seems that the local video track is created but can not to be rendered on the local view. Does there anybody have the same issue with me?

**Comment by kolencherry** [comment]
We do not provide support for WebRTC-related issues. I'd recommend posting in the discuss-webrtc Google Group, linked below.

https://groups.google.com/forum/#!forum/discuss-webrtc
