### ISSUE TITLE
get_webrtc fails with 'gyp_webrtc.py -Dextra_gyp_flag=0 returned non-zero exit status 1' error.

### ISSUE THREAD

**Issue by applegrew** [pristineio/webrtc-build-scripts#181]
I am running the build scripts in VirtualBox with Ubuntu 14.04 64-bit. After resolving numerous errors, finally I am stuck at this:-

	________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' in '/media/ag/External HD/webrtc-build-scripts-master/android/webrtc'
	2> Downloading src/resources/far44_stereo.pcm...
	5> Downloading src/resources/verizon3g-downlink.rx...
	1> Downloading src/resources/audioproc.aecdump...
	6> Downloading src/resources/paris_qcif.yuv...
	0> Downloading src/resources/far48_stereo.pcm...
	8> Downloading src/resources/short_mixed_stereo_48.dat...
	3> Downloading src/resources/near32_stereo.pcm...
	......
	0> Downloading src/resources/rtp_rtcp/RTCPPacketTMMBR0.bin...
	9> Downloading src/resources/rtp_rtcp/H263Foreman_CIF_Pframe.bin...
	Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' took 606.83 secs

	________ running '/usr/bin/python src/webrtc/build/gyp_webrtc.py -Dextra_gyp_flag=0' in '/media/ag/External HD/webrtc-build-scripts-master/android/webrtc'
	Updating projects from gyp files...
	gyp: Call to './build/linux/sysroot_ld_path.sh /media/ag/External HD/webrtc-build-scripts-master/android/webrtc/src/build/linux/debian_wheezy_amd64-sysroot' returned exit status 1 while in all.gyp.
	Error: Command '/usr/bin/python src/webrtc/build/gyp_webrtc.py -Dextra_gyp_flag=0' returned non-zero exit status 1 in /media/ag/External HD/webrtc-build-scripts-master/android/webrtc

**Tips for others**, if you are using VirtualBox. Make sure to allocate atleast 2GB of RAM else git will die with code -9. Also make sure to use 64-bit Ubuntu not 32-bit. And do not use shared folders. The folder where you run these commands should be a VirtualBox HDD. On Shared folders symlinks creation will fail.

One more question, everywhere I see that the total size could be around 5-6GB, but for me it is 28GB and still counting!

**Comment by applegrew** [comment]
It went away when re-ran `get_webrtc`.

**Comment by notedit** [comment]
still have this error  with get_webrtc.

can you share your latest  build lib?
