### ISSUE TITLE
How to get a built version of webrtc for iOS

### ISSUE THREAD

**Issue by KamyarGhajar** [pristineio/webrtc-build-scripts#185]
Hi,
Is there another way to use webrtc in a native app without downloading the chromium tools (my connection is not really good and it got disconnected many times)
Is there a built sdk or library to just use it in the Xcode project?
besides I assume the cocoa pods way still needs the chromium heavy download...

**Comment by WisdomShadow** [comment]
or Is there a way to download these heavy chromium thing as a zip file or a direct link to download it all with a download manager?

**Comment by MikeBlair** [comment]
Yes, there is a prebuilt cocoapod available here: https://cocoapods.org/pods/libjingle_peerconnection

You can look at this Github project for an example of how the cocoapod can be used: https://github.com/webrtc/apprtc

**Comment by KamyarGhajar** [comment]
Thanks...I'll look up on to it.
