### ISSUE TITLE
Interest in contributing to webrtc-build-scripts

### ISSUE THREAD

**Issue by atsakiridis** [pristineio/webrtc-build-scripts#186]
Hello all,

Sorry for opening an issue for this, but didn't know how else to reach you

So, we 've been building open source mobile webrtc SDKs at Telestax (you can check https://github.com/RestComm/restcomm-ios-sdk, and https://github.com/RestComm/restcomm-android-sdk) and have been using your build scripts from time to time (I once contributed a PR as well), as building libjingle libs can be a pain as you no doubt know, so first off let me say thank you :)

Anyway, since I'm already spending time on this, I thought it would be better if we could join forces and collaborate on this. Do you think we could discuss this offline?

Also, do you guys have a roadmap on where this is going and how interested contributors could best assist the webrtc community with the build scripts? Seems there's so much interest out there!

Best regards,
Antonis Tsakiridis

**Comment by kolencherry** [comment]
Antonis,

Could you shoot me an email at my first name at pristine.io?
