### ISSUE TITLE
Audio distorted or missing

### ISSUE THREAD

**Issue by antoniotuzzi** [pristineio/webrtc-build-scripts#188]
Hello @pristineio friends !

last revision fully working audio for me is the **r9181**

if I use any of the revisions after **r10000** I'm getting or missing audio, or distorted audio
this is happening on iOS, I didn't test on Android

If I compile, or if I use prebuilt binaries, I have same results:
a) if both devices are using a "faulty" release, I can hear just a "pop" at the start of the communication
b) if of the 2 devices is using a **r9181**, the faulty one, receives the audio, but in someway distorted. To me seems doubled, like somewhere in the code is counting "bytes" instead of "frames" (classical error in audio rendering path)

Maybe there was some change in the webRTC protocol after **r10000** and I'm unaware of it ?

**Comment by ArikYa** [comment]
This sounds like WebRTC issue, this repo is only for the build scripts. You
should ask on their discussion board

**Comment by antoniotuzzi** [comment]
yes is definitively a WebRTC issue, but is confined only to the emulator. And is happening to revisions done AFTER August 30th 2015
