### ISSUE TITLE
getting audio samples from RTCAudioTrack

### ISSUE THREAD

**Issue by antoniotuzzi** [pristineio/webrtc-build-scripts#189]
Hello friends

Is there any trick to get **samples from a running audio_device** on iOS or Android ?

I'd like to do some statistical analysis on the audio, or maybe reuse it, or more, record it locally

thanks

**Comment by ArikYa** [comment]
This kind of questions are better answered in https://groups.google.com/forum/#!forum/discuss-webrtc
