### ISSUE TITLE
Build  for iOS has linker error

### ISSUE THREAD

**Issue by chebur** [pristineio/webrtc-build-scripts#190]
I've built webrtc #13094 for iOS using your scripts. Everything was fine, but I'm keep getting the following linker errors when integrating it into my project. What exactly am I missing here? 

Also, I'm not using any video features in the app. Can I disable it completely before running build scripts?

```
Undefined symbols for architecture x86_64:
  "webrtc::metrics::HistogramAdd(webrtc::metrics::Histogram*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      webrtc::internal::Call::UpdateSendHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.call.o)
      webrtc::internal::Call::UpdateReceiveHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.call.o)
      webrtc::SendDelayStats::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.send_delay_stats.o)
      webrtc::CallStats::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.call_stats.o)
      webrtc::AudioProcessingImpl::MaybeUpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(audio_processing.audio_processing_impl.o)
      webrtc::AudioProcessingImpl::UpdateHistogramsOnCallEnd() in libWebRTC-13094-arm-intel-Release.a(audio_processing.audio_processing_impl.o)
      webrtc::RtpStreamReceiver::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.rtp_stream_receiver.o)
      ...
  "webrtc::metrics::HistogramFactoryGetCounts(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int)", referenced from:
      webrtc::internal::Call::UpdateSendHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.call.o)
      webrtc::internal::Call::UpdateReceiveHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.call.o)
      webrtc::SendDelayStats::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.send_delay_stats.o)
      webrtc::CallStats::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.call_stats.o)
      webrtc::AudioProcessingImpl::MaybeUpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(audio_processing.audio_processing_impl.o)
      webrtc::ScreenshareLayers::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc_vp8.screenshare_layers.o)
      webrtc::SendStatisticsProxy::UmaSamplesContainer::UpdateHistograms(webrtc::VideoSendStream::Config const&, webrtc::VideoSendStream::Stats const&) in libWebRTC-13094-arm-intel-Release.a(webrtc.send_statistics_proxy.o)
      ...
  "webrtc::metrics::HistogramFactoryGetEnumeration(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      webrtc::AudioProcessingImpl::UpdateHistogramsOnCallEnd() in libWebRTC-13094-arm-intel-Release.a(audio_processing.audio_processing_impl.o)
      webrtc::RtpStreamReceiver::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.rtp_stream_receiver.o)
      webrtc::SendStatisticsProxy::SendStatisticsProxy(webrtc::Clock*, webrtc::VideoSendStream::Config const&, webrtc::VideoEncoderConfig::ContentType) in libWebRTC-13094-arm-intel-Release.a(webrtc.send_statistics_proxy.o)
      webrtc::SendStatisticsProxy::UmaSamplesContainer::UpdateHistograms(webrtc::VideoSendStream::Config const&, webrtc::VideoSendStream::Stats const&) in libWebRTC-13094-arm-intel-Release.a(webrtc.send_statistics_proxy.o)
      webrtc::ReceiveStatisticsProxy::UpdateHistograms() in libWebRTC-13094-arm-intel-Release.a(webrtc.receive_statistics_proxy.o)
      webrtc::acm2::AudioCodingModuleImpl::Encode(webrtc::acm2::AudioCodingModuleImpl::InputData const&) in libWebRTC-13094-arm-intel-Release.a(audio_coding_module.audio_coding_module_impl.o)
      webrtc::VCMTiming::UpdateHistograms() const in libWebRTC-13094-arm-intel-Release.a(webrtc_video_coding.timing.o)
      ...
```

**Comment by DSaurabh** [comment]
I am also facing similar issue. After including "AudioUnit.framework" error is not coming but i am getting framework not found. 
Error:-
ld: framework not found AudioUnit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

including AudioToolbox.framework or CoreAudioKit.framework did not worked.

**Comment by Lenne231** [comment]
You can find the explanation for the issue here: https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/webrtc/system_wrappers/include/metrics.h

**Comment by chebur** [comment]
Thanks for useful link. I've implemented those methods and it seems everything goes fine.

**Comment by DSaurabh** [comment]
Hi chebur,
Can you please share the implementation file this issue.

**Comment by chebur** [comment]
```c++
#include <string>

namespace webrtc {
    namespace metrics {
        class Histogram;

        // Implementation of histogram methods in
        // webrtc/system_wrappers/interface/metrics.h.
        Histogram* HistogramFactoryGetCounts(const std::string& name,
                                             int min,
                                             int max,
                                             int bucket_count) {
            return nullptr;
        }
        
        Histogram* HistogramFactoryGetEnumeration(const std::string& name,
                                                  int boundary) {
            return nullptr;
        }
        
        void HistogramAdd(Histogram* histogram_pointer,
                          const std::string& name,
                          int sample) {
            return;
        }
    }
}
```

**Comment by utkarshs07** [comment]
I'm having same issue when updated to **Revision 13207**

`Undefined symbols for architecture arm64:
  "webrtc::metrics::HistogramFactoryGetEnumeration(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      webrtc::AudioProcessingImpl::UpdateHistogramsOnCallEnd() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::(anonymous namespace)::AudioCodingModuleImpl::Add10MsData(webrtc::AudioFrame const&) in WebRTC(audio_coding_module.audio_coding_module.o)
      webrtc::RtpStreamReceiver::UpdateHistograms() in WebRTC(webrtc.rtp_stream_receiver.o)
      webrtc::SendStatisticsProxy::SendStatisticsProxy(webrtc::Clock*, webrtc::VideoSendStream::Config const&, webrtc::VideoEncoderConfig::ContentType) in WebRTC(webrtc.send_statistics_proxy.o)
      webrtc::SendStatisticsProxy::UmaSamplesContainer::UpdateHistograms(webrtc::VideoSendStream::Config const&, webrtc::VideoSendStream::Stats const&) in WebRTC(webrtc.send_statistics_proxy.o)
      webrtc::ReceiveStatisticsProxy::UpdateHistograms() in WebRTC(webrtc.receive_statistics_proxy.o)
      webrtc::VCMTiming::UpdateHistograms() const in WebRTC(webrtc_video_coding.timing.o)
      ...
  "webrtc::metrics::HistogramFactoryGetCounts(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int)", referenced from:
      webrtc::internal::Call::UpdateSendHistograms() in WebRTC(webrtc.call.o)
      webrtc::internal::Call::UpdateReceiveHistograms() in WebRTC(webrtc.call.o)
      webrtc::SendDelayStats::UpdateHistograms() in WebRTC(webrtc.send_delay_stats.o)
      webrtc::CallStats::UpdateHistograms() in WebRTC(webrtc.call_stats.o)
      webrtc::AudioProcessingImpl::MaybeUpdateHistograms() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::(anonymous namespace)::AudioCodingModuleImpl::Add10MsData(webrtc::AudioFrame const&) in WebRTC(audio_coding_module.audio_coding_module.o)
      webrtc::ScreenshareLayers::UpdateHistograms() in WebRTC(webrtc_vp8.screenshare_layers.o)
      ...
  "webrtc::metrics::HistogramAdd(webrtc::metrics::Histogram*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      webrtc::internal::Call::UpdateSendHistograms() in WebRTC(webrtc.call.o)
      webrtc::internal::Call::UpdateReceiveHistograms() in WebRTC(webrtc.call.o)
      webrtc::SendDelayStats::UpdateHistograms() in WebRTC(webrtc.send_delay_stats.o)
      webrtc::CallStats::UpdateHistograms() in WebRTC(webrtc.call_stats.o)
      webrtc::AudioProcessingImpl::MaybeUpdateHistograms() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::AudioProcessingImpl::UpdateHistogramsOnCallEnd() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::(anonymous namespace)::AudioCodingModuleImpl::Add10MsData(webrtc::AudioFrame const&) in WebRTC(audio_coding_module.audio_coding_module.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`


The implementation of above three methods, where should i put them?

because **metrics_default.c** has the implementation of these methods, so should i link **include/metrics_default.h** and **source/metrics_default.c** in **system_wrappers.gyp** ??
