### ISSUE TITLE
iOS: Undefined symbols for architecture arm64: Revision 13207

### ISSUE THREAD

**Issue by utkarshs07** [pristineio/webrtc-build-scripts#193]
I'm having arch issue when updated to **Revision 13207**

`Undefined symbols for architecture arm64:
  "webrtc::metrics::HistogramFactoryGetEnumeration(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      webrtc::AudioProcessingImpl::UpdateHistogramsOnCallEnd() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::(anonymous namespace)::AudioCodingModuleImpl::Add10MsData(webrtc::AudioFrame const&) in WebRTC(audio_coding_module.audio_coding_module.o)
      webrtc::RtpStreamReceiver::UpdateHistograms() in WebRTC(webrtc.rtp_stream_receiver.o)
      webrtc::SendStatisticsProxy::SendStatisticsProxy(webrtc::Clock*, webrtc::VideoSendStream::Config const&, webrtc::VideoEncoderConfig::ContentType) in WebRTC(webrtc.send_statistics_proxy.o)
      webrtc::SendStatisticsProxy::UmaSamplesContainer::UpdateHistograms(webrtc::VideoSendStream::Config const&, webrtc::VideoSendStream::Stats const&) in WebRTC(webrtc.send_statistics_proxy.o)
      webrtc::ReceiveStatisticsProxy::UpdateHistograms() in WebRTC(webrtc.receive_statistics_proxy.o)
      webrtc::VCMTiming::UpdateHistograms() const in WebRTC(webrtc_video_coding.timing.o)
      ...
  "webrtc::metrics::HistogramFactoryGetCounts(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int)", referenced from:
      webrtc::internal::Call::UpdateSendHistograms() in WebRTC(webrtc.call.o)
      webrtc::internal::Call::UpdateReceiveHistograms() in WebRTC(webrtc.call.o)
      webrtc::SendDelayStats::UpdateHistograms() in WebRTC(webrtc.send_delay_stats.o)
      webrtc::CallStats::UpdateHistograms() in WebRTC(webrtc.call_stats.o)
      webrtc::AudioProcessingImpl::MaybeUpdateHistograms() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::(anonymous namespace)::AudioCodingModuleImpl::Add10MsData(webrtc::AudioFrame const&) in WebRTC(audio_coding_module.audio_coding_module.o)
      webrtc::ScreenshareLayers::UpdateHistograms() in WebRTC(webrtc_vp8.screenshare_layers.o)
      ...
  "webrtc::metrics::HistogramAdd(webrtc::metrics::Histogram*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      webrtc::internal::Call::UpdateSendHistograms() in WebRTC(webrtc.call.o)
      webrtc::internal::Call::UpdateReceiveHistograms() in WebRTC(webrtc.call.o)
      webrtc::SendDelayStats::UpdateHistograms() in WebRTC(webrtc.send_delay_stats.o)
      webrtc::CallStats::UpdateHistograms() in WebRTC(webrtc.call_stats.o)
      webrtc::AudioProcessingImpl::MaybeUpdateHistograms() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::AudioProcessingImpl::UpdateHistogramsOnCallEnd() in WebRTC(audio_processing.audio_processing_impl.o)
      webrtc::(anonymous namespace)::AudioCodingModuleImpl::Add10MsData(webrtc::AudioFrame const&) in WebRTC(audio_coding_module.audio_coding_module.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by KamyarGhajar** [comment]
I have the same problem. Does anyone know how to fix this?...Is there a setting that must be set in build/common.gypi or sth else?

**Comment by yingzhuo1314** [comment]
I have the same problem. Does anyone know how to fix this?

**Comment by KamyarGhajar** [comment]
I think I just fixed the problem in my case (Build a Framework with added codes to RTC in a Swift Project)...I synced my webrtc folder with 'gclient sync' then enabled the bit code compilation for building the .a files in webrtc/build/common.gypi...then added `clang_xcode=1` to `GYP_DEFINES` in build.sh file in iOS folder and enabled the bit code compilation in Xcode project's build settings...follow these instructions if needed : https://blog.andyet.com/2015/10/20/building-webrtc-with-bitcode/

Please inform me if this did work for you too...

**Comment by utkarshs07** [comment]
I solved it. 

We need to provide implementation of these methods:

       Histogram* HistogramFactoryGetCounts(const std::string& name,
                                             int min,
                                             int max,
                                             int bucket_count) 

        Histogram* HistogramFactoryGetEnumeration(const std::string& name,
                                                  int boundary) 

        void HistogramAdd(Histogram* histogram_pointer,
                          const std::string& name,
                          int sample)

Create an implementation file named **metrics.cc** under webrtc-->system_wrappers-->source
and add this code:

     #include "webrtc/system_wrappers/include/metrics_default.h"

     #include "webrtc/base/criticalsection.h"
     #include "webrtc/base/thread_annotations.h"
     #include "webrtc/system_wrappers/include/metrics.h"

    // Default implementation of histogram methods for WebRTC clients that do not
    // want to provide their own implementation.

    #include <string>

     namespace webrtc {
          namespace metrics {
              class Histogram;

           // Implementation of histogram methods in
          // webrtc/system_wrappers/interface/metrics.h.
         Histogram* HistogramFactoryGetCounts(const std::string& name,
                                             int min,
                                             int max,
                                             int bucket_count) {
            return nullptr;
        }

        Histogram* HistogramFactoryGetEnumeration(const std::string& name,
                                                  int boundary) {
            return nullptr;
        }

        void HistogramAdd(Histogram* histogram_pointer,
                          const std::string& name,
                          int sample) {
            return;
        }
    }
    }

open **system_wrappers.gyp** and add **include/metrics.h** under sources
save it and repeat build process.

**Comment by saghul** [comment]
@utkarshs07 at least revision XXXX contains a default implementation, but it's not built for the system_wrappers target, the system_wrappers_default target must be explicitly built.

A quick way to get around this is to add the sources for the default implementations to the regular target:

~~~~
diff --git a/webrtc/system_wrappers/system_wrappers.gyp b/webrtc/system_wrappers/system_wrappers.gyp
index ea8fdb6..8ced6b2 100644
--- a/webrtc/system_wrappers/system_wrappers.gyp
+++ b/webrtc/system_wrappers/system_wrappers.gyp
@@ -76,6 +76,8 @@
         'source/trace_posix.h',
         'source/trace_win.cc',
         'source/trace_win.h',
+        'include/metrics_default.h',
+        'source/metrics_default.cc',
       ],
       'conditions': [
         ['enable_data_logging==1', {
~~~~

**Comment by saghul** [comment]
The revision I successfully built as stated above is 13311.

**Comment by notedit** [comment]
@saghul  can you give an android version ?  

this build script can not work for the latest webrtc code

**Comment by saghul** [comment]
@notedit I can't, as I've never compiled it for Android, sorry :-( It's possible that the fix also works for Android though!

**Comment by saghul** [comment]
@utkarshs07 Why close this? There is no builtin patch provided to fix this, so everyone will have to scratch their heads and end up eventually finding this issue with the solution, which is not really ideal IMHO.
