### ISSUE TITLE
Revision 13207: iOS h264 support

### ISSUE THREAD

**Issue by utkarshs07** [pristineio/webrtc-build-scripts#196]
I want to add **H264** support in iOS so i've added flag **use_objc_h264=1** under **gyp_defines** in function **wrios_armv8()** (for 64-bit devices).

I've also modified my **sdp** for H264 video codec but when place video call both sides **RTCEAGLVideoView** showing green color not remote videos. 

I've also verified through WebRTC stats report. It's saying that sending and receiving both video codecs are H264.

Testing with iPhone 5s and iPhone 6plus.

can anyone help me, is there something wrong with build process or something i am missing in implementation..?

**Comment by ArikYa** [comment]
This kind of questions is better answered in https://groups.google.com/forum/#!forum/discuss-webrtc
