### ISSUE TITLE
iOS: Video is a green rectangle (H.264)

### ISSUE THREAD

**Issue by x3mall1986** [pristineio/webrtc-build-scripts#198]
Hi. I have small problem with h264 codec. 13524 revision of libWebRTC and enabled **use_objc_h264** flag. 
When using other codecs - video stream is working. 
iOS 9.3.3, 
iPhones: 5s & 6s+
![img_3509](https://cloud.githubusercontent.com/assets/1582648/17140273/8e77092e-5350-11e6-999b-3a31516f55c8.jpg)

**If somebody knows about this please help.**

**Comment by notedit** [comment]
you are not alone  https://github.com/pristineio/webrtc-build-scripts/issues/196

**Comment by ArikYa** [comment]
Guys, this repo only handles build scripts, for any issues with the workings of WebRTC, please use their discussion forum or bug tracker

**Comment by x3mall1986** [comment]
In sample WebRTCDemo from WebRTC site - video with codec h264 work fine.

**Comment by utkarshs07** [comment]
@x3mall1986 hey ... you've figured it out? I'm also looking into it.

**Comment by x3mall1986** [comment]
@utkarshs07 so...so. Searching now way to compile. 
It's my question on google discuss-webrtc. 
https://groups.google.com/forum/#!topic/discuss-webrtc/P8giZQEkX4U

And on this link is some info about using new sources: https://groups.google.com/forum/#!topic/discuss-webrtc/Pt3gKgi56J8

**Comment by utkarshs07** [comment]
@x3mall1986 so they are saying that talk/app/webrtc/objc/ is not suitable anymore. I think they recently added the framework section.

do you know how to pull out that framework?

**Comment by x3mall1986** [comment]
https://github.com/Anakros/WebRTC-iOS

**Comment by utkarshs07** [comment]
@x3mall1986 thanks a lot! but still have one doubt.

this framework includes webrtc native code like libWebRTC_intel_release.a OR just only objC code (.h & .m) of SDK section?

**Comment by x3mall1986** [comment]
@utkarshs07  I don't know. You can ask it in this thread 
https://groups.google.com/forum/#!topic/discuss-webrtc/Pt3gKgi56J8
