### ISSUE TITLE
No more libjingle_peerconnection pod?

### ISSUE THREAD

**Issue by manuroe** [pristineio/webrtc-build-scripts#202]
Hello,
Did you stop to maintain this useful pod?
There were plenty of libjingle_peerconnection pod releases until they suddenly stopped in January 2016.

**Comment by Anakros** [comment]
Take a look at this: https://github.com/Anakros/WebRTC-iOS

**Comment by manuroe** [comment]
Thanks @Anakros. Your build of WebRTC works like a charm.
