### ISSUE TITLE
libRTC for tvOS

### ISSUE THREAD

**Issue by beastgrim** [pristineio/webrtc-build-scripts#205]
Hello !!!

It is possible add scripts for building libRTC for Apple TV (tvOS)?
Because I can't link iOS lib in an apple tv app (

Thanks!

**Comment by Tonku** [comment]
No answer...!!!

**Comment by phatware** [comment]
ahhhhrrr.... Anybody? I really do not want to waist my time creating script for tvOS :) I mean, seriously, somebody must have compiled webRTC for tvOS it by now!

**Comment by kolencherry** [comment]
This isn't possible at the time and will not be done by the maintainers of this repo. 

As a side note, in general, getting WebRTC working on tvOS is better suited for discuss-webrtc.

@ArikYa, could you please close this issue and mark as wontfix?
