### ISSUE TITLE
Error occur when executing 'install_dependencies'

### ISSUE THREAD

**Issue by o3661606** [pristineio/webrtc-build-scripts#206]
Line 47 in android/build.sh

curl -o install-build-deps-android.sh https://src.chromium.org/svn/trunk/src/build/install-build-deps-android.sh

the above command does not work anymore, producing HTTP404 error

**Comment by ArikYa** [comment]
Can you try with the latest version? it was updated yesterday

**Comment by o3661606** [comment]
now it works, thanks.
