### ISSUE TITLE
Error occurs when executing 'build_apprtc' 

### ISSUE THREAD

**Issue by o3661606** [pristineio/webrtc-build-scripts#212]
**Error occurs when executing 'build_apprtc'** 
Using: Ubuntu 14.04
Below is the log extract, **same error will occur in the other 3 platforms (armv8, x86, x86_64)** :

> Setting up build environment for Android
> Export the base settings of GYP_DEFINES so we can define how we want to build
> User has not specified any gyp defines so we proceed with default
> GYP_DEFINES=
> Generate projects using GN
> ERROR at //build/config/android/rules.gni:2619:9: Script returned non-zero exit code.
>         exec_script("//build/android/gyp/aar.py",
>         ^----------
> Current dir: /home/mike/webrtc-build-scripts/android/webrtc/src/out_android_arm/Debug/
> Command: python -- /home/mike/webrtc-build-scripts/android/webrtc/src/build/android/gyp/aar.py --input-file ../../third_party/android_tools/sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/9.8.0/play-services-basement-9.8.0.aar --list
> Returned 1.
> stderr:
> 
> Traceback (most recent call last):
>   File "/home/mike/webrtc-build-scripts/android/webrtc/src/build/android/gyp/aar.py", line 109, in <module>
>     sys.exit(main())
>   File "/home/mike/webrtc-build-scripts/android/webrtc/src/build/android/gyp/aar.py", line 80, in main
>     with zipfile.ZipFile(aar_file) as z:
>   File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
>     self.fp = open(file, modeDict[mode])
> IOError: [Errno 2] No such file or directory: '../../third_party/android_tools/sdk/extras/google/m2repository/com/google/android/gms/play-services-basement/9.8.0/play-services-basement-9.8.0.aar'
> 
> See //third_party/android_tools/BUILD.gn:150:1: whence it was called.
> android_aar_prebuilt("google_play_services_basement_java") {
> ^-----------------------------------------------------------
> See //webrtc/system_wrappers/BUILD.gn:158:7: which caused the file to be included.
>       "//third_party/android_tools:cpu_features",
>       ^-----------------------------------------
> Build AppRTCMobile in Debug (arch: armeabi-v7a)
> Running ninja
> ninja: Entering directory `out_android_arm/Debug'
> ninja: error: loading 'build.ninja': No such file or directory
> Debug build for apprtc failed for revision 14935
>

**Comment by o3661606** [comment]
@ArikYa Can you please take a look on this issue?

**Comment by ArikYa** [comment]
I just tested with the latest revision and it worked for me. Take notice that when running 'gclient sync/runhooks' you might need to respond to the Google Play Services EULA, or it won't download it. That might be the issue in your case
