### ISSUE TITLE
Error at "Adding a new libWebRTC_objc target"

### ISSUE THREAD

**Issue by Jun711** [pristineio/webrtc-build-scripts#231]
I guess this is the reason that I got the following error message? 

##PSA - WebRTC builds have moved to using GN instead of GYP. Android build script is adapted, but iOS script is still break. Feel free to fork and update them.

`Adding a new libWebRTC_objc target
/Users/usr/webrtc-build-scripts/ios/insert_two_lines_after_text.py
Traceback (most recent call last):
  File "/Users/usr/webrtc-build-scripts/ios/insert_two_lines_after_text.py", line 33, in <module>
    if isStringAlreadyAppended(FILE, APPEND):
  File "/Users/usr/webrtc-build-scripts/ios/insert_two_lines_after_text.py", line 29, in isStringAlreadyAppended
    with open(f) as content:
IOError: [Errno 2] No such file or directory: '/Users/usr/webrtc-build-scripts/ios/webrtc/src/webrtc/webrtc_examples.gyp'
-- webrtc has been successfully updated
`
Does this fork have the fix for this? 
https://github.com/RishatShamsutdinov/webrtc-build-scripts

has anyone else tried? Thank you!

**Comment by ArikYa** [comment]
I had a quick look at the repository you linked to, and it definitely seems he got it right for the latest WebRTC builds. Feel free to use that one!
