### ISSUE TITLE
build_apprtc for Android causes "die: error: must run as root" for ninja

### ISSUE THREAD

**Issue by soulfly** [pristineio/webrtc-build-scripts#27]
build_apprtc for Android causes "die: error: must run as root" for ninja

Here what I see in logs:

     Build AppRTCDemo in  (arch: x86_64) mode
     log: ninja version 0.1.3 initializing
     die: error: must run as root

**Comment by smithaaron** [comment]
I'm also getting this error.

**Comment by aaalaniz** [comment]
@soulfly what exactly are you executing? I just pulled down latest and ran the following and it worked.

```shell

get_webrtc && build_apprtc

```

**Comment by smithaaron** [comment]
FWIW I had forgotten to run install_dependencies. Perhaps same issue for OP?

**Comment by efecannn** [comment]
linux(ubuntu) on:
sudo apt-get remove --purge ninja

**Comment by HEllRZA** [comment]
```
sudo apt remove --purge ninja
sudo apt install ninja-build
```
