### ISSUE TITLE
iOS - crash: change camera feed while on the call

### ISSUE THREAD

**Issue by calitb** [pristineio/webrtc-build-scripts#36]
What's the right way to switch the camera from the front-camera to the rear-camera while the call is going.

I tried this, it works a few times, then it crashes. Any idea why?

[self.localVideoTrack removeRenderer:(RTCEAGLVideoView*)[self.viewController localVideoTrackViewForCallController:self]];
            
            RTCMediaStream* lms = self.peerConnection.localStreams[1];
            [lms removeVideoTrack:self.localVideoTrack];
            [self.peerConnection removeStream:lms];
            
            NSString *newVideoTrackId = nil;
            NSString *oldVideoTrackId = nil;
            if (_rearCamera) {
                oldVideoTrackId = @"ARDAMSv1";
                newVideoTrackId = @"ARDAMSv0";
            }
            else {
                oldVideoTrackId = @"ARDAMSv0";
                newVideoTrackId = @"ARDAMSv1";
            }
            
            RTCVideoCapturer* capturer = [RTCVideoCapturer capturerWithDeviceName:newCameraID];
            self.videoSource = [_peerConnectionFactory videoSourceWithCapturer:capturer constraints:self.videoConstraints];
            self.localVideoTrack = [_peerConnectionFactory videoTrackWithID:newVideoTrackId source:self.videoSource];
            
            [lms addVideoTrack:self.localVideoTrack];
            [self.peerConnection addStream:lms];
            
            RTCSessionDescription* remoteDesc = self.peerConnection.remoteDescription;
            RTCSessionDescription *localDesc = [[RTCSessionDescription alloc] initWithType:self.peerConnection.localDescription.type sdp:[self.peerConnection.localDescription.description stringByReplacingOccurrencesOfString:oldVideoTrackId withString:newVideoTrackId]];
            
                [self.peerConnection setLocalDescriptionWithDelegate:self sessionDescription:localDesc];
                [self.peerConnection setRemoteDescriptionWithDelegate:self sessionDescription:remoteDesc];

**Comment by paynerc** [comment]
I think you would have better luck opening an issue with the WebRTC issue tracker (https://code.google.com/p/webrtc/issues) as this deals more with the workings of WebRTC itself and not these scripts for building it.

**Comment by calitb** [comment]
thanks, you are right. I added the issue there. closing here
