### ISSUE TITLE
iOS: Missing x86_64 Symbols

### ISSUE THREAD

**Issue by dylansturg** [pristineio/webrtc-build-scripts#37]
I'm using the provided build scrips (thanks by the way!) to build a WebRTC library and I'm adding into my own project.  When I try to include arm64 in the valid architectures for the project, I receive linker warnings regarding missing symbols for x86_64.  I think that is because the simulator uses x86_64 (I'm pretty new to iOS...) the library built by default seems to only have arm7, arm64, and i386.  Is it possible to get it built and working for arm64/x86_64 in an iOS project?

As background, I think Apple is going to start requiring projects use arm64 and want to make sure my project conforms to their standard.

**Comment by dylansturg** [comment]
That sounds like a simple enough short-term solution.  Thank you @calitb !

**Comment by temahussain** [comment]
I am trying to build for 64-bit simulator using target_arch=x64 but it is giving me the following error:

../../chromium/src/third_party/nss/nss/lib/freebl/poly1305/poly1305-donna-x64-sse2-incremental-source.c:23:18: error: __int128 is not supported on this target
typedef unsigned __int128 uint128_t;

Do I need to do anything special?

Any help would be appreciated

**Comment by thebehera** [comment]
Out of curiosity what's the value of compiling a 64 bit webrtc library for the simulator? In cocoapods, the builds include ARM64, ARM32, and x86 (Simulator)... that should cover all grounds

**Comment by rwickliffe** [comment]
Another option I've used successfully is setting the Valid Architectures per SDK as follows:

```
//:configuration = Debug
VALID_ARCHS = armv7 arm64
VALID_ARCHS[sdk=iphonesimulator*] = armv7
VALID_ARCHS[sdk=iphoneos*] = armv7 arm64
```

![image](https://cloud.githubusercontent.com/assets/1671881/5638531/6b91c45e-95cd-11e4-9e3a-97e1774d009f.png)

**Comment by temahussain** [comment]
@thebehera: target_arch=x64 target_subarch=x64

This will compile for both i386 (32-bit simulator) and x86_64 (64-bit simulator)

But with webrtc r7887 I am getting the error mentioned above. Though it compiles successfully for target_arch=ia32

**Comment by calitb** [comment]
@rwickliffe great solution
