### ISSUE TITLE
iOS:Can't build?

### ISSUE THREAD

**Issue by szhuangzan** [pristineio/webrtc-build-scripts#39]
awk: illegal primary in regular expression ) |" at  |"
 input record number 1, file 
 source line number 1
Using code signing identity
sed: /Users/huangzan/Downloads/webrtc-build-scripts/webrtc-build-scripts/ios/webrtc/src/build/common.gypi: No such file or directory
.gclient file in parent directory /Users/huangzan/Downloads/webrtc-build-scripts/webrtc-build-scripts/ios/webrtc might not be the file you want to use

________ running '/usr/bin/python -c import os,sys;script = os.path.join("trunk","check_root_dir.py");_ = os.system("%s %s" % (sys.executable,script)) if os.path.exists(script) else 0' in '/Users/huangzan/Downloads/webrtc-build-scripts/webrtc-build-scripts/ios/webrtc'

________ running '/usr/bin/python -u src/sync_chromium.py --target-revision 271c6cca48a6cef32c0f3add3b17b700707deec5' in '/Users/huangzan/Downloads/webrtc-build-scripts/webrtc-build-scripts/ios/webrtc'
Running "gclient sync --force --revision src@271c6cca48a6cef32c0f3add3b17b700707deec5 --gclientfile .gclient.tmp --delete_unversioned_trees --reset --upstream --deps=ios,mac" in /Users/huangzan/Downloads/webrtc-build-scripts/webrtc-build-scripts/ios/webrtc/src/chromium
[0:01:00] Still working on:
[0:01:00]   src
[0:01:10] Still working on:
[0:01:10]   src
[0:01:20] Still working on:
[0:01:20]   src
[0:01:30] Still working on:

XCODE 6.1.1

**Comment by thebehera** [comment]
I just took out the awk command because it was breaking but should be ok now. Try pulling to the latest master and running the command again.
