### ISSUE TITLE
Awk error obtaining signing identity

### ISSUE THREAD

**Issue by zero1zero** [pristineio/webrtc-build-scripts#41]
When running build_webrtc or build_webrtc_mac, I am getting an awk error obtaining a signing identity.  This looks to be most likely whats making my builds fail.

    awk: illegal primary in regular expression ) |" at  |"
     input record number 1, file
     source line number 1
    Using code signing identity

Been trying to play around with the syntax to get it to work but haven't been getting anywhere. I figured it would be a simple escaping issue but escaping those characters didn't work.  Of note: I am using zsh but was able to reproduce on bash as well.

**Comment by zero1zero** [comment]
Might be of note:

    ± % awk --version                                                                                                                                                                                                                                                                                                                                                    
        awk version 20070501

**Comment by thebehera** [comment]
Absolutely @rspeyer was the original author. I ended up commenting it out for now but I think we need a better more native solution without requiring the users to update

**Comment by thebehera** [comment]
does your fix work?

**Comment by zero1zero** [comment]
It does on my machine. Wanted to make sure it wasn't something obvious before submitting a PR with it.

**Comment by zero1zero** [comment]
Does on my machine. Do you have a more current version of awk that you can test it on?  If so I can submit the PR.

**Comment by thebehera** [comment]
Rahuls-MacBook-Pro:signaling-ios rbehera$ awk --version
awk version 20070501

nope. I have the same on my machine. I'm suprised Apple would leave such outdated versions

**Comment by rspeyer** [comment]
Thanks @zero1zero - it seems to be working for me and I am running  a much newer version of awk (obtained via Homebrew). It does spit out the following warning, but ends up working:
```
awk: warning: escape sequence `\)' treated as plain `)'
Using code signing identity iPhone Developer: Richard Speyer (XXXXXXX)
```

**Comment by thebehera** [comment]
@zero1zero would you mind opening a pull request?
