### ISSUE TITLE
awk error during get_webrtc of ios

### ISSUE THREAD

**Issue by EricDavies** [pristineio/webrtc-build-scripts#45]
I've pulled down the build scripts from the master branch today (so that would be commit 7570628c93). I'm trying to build for iOS. Both get_webrtc and build_webrtc are generating the message below (illegal primary in regular expression). Hopefully it's not harmful.

.....
Get the current working directory so we can change directories back when done
If no directory where depot tools should be...
Change directory into the depot tools
Pull the depot tools down to the latest
Already up-to-date.
Go back to working directory
awk: illegal primary in regular expression ) |" at  |"
 input record number 1, file 
 source line number 1
Using code signing identity
....

**Comment by paynerc** [comment]
Seems like this is [a similar|the same] issue reported in #41?
