### ISSUE TITLE
Update maven artifact

### ISSUE THREAD

**Issue by growlsworth** [pristineio/webrtc-build-scripts#48]
Hey pristine.io,

Any chance you can push an updated version of your libjingle maven artifact? I've been downloading the webrtc source for the past 16 hours and it's still not done. 

Thanks.

Here's a picture of two adorable baby platypuses to encourage you to update the artifact:

![baby platipuses](http://cdn.cutestpaw.com/wp-content/uploads/2012/01/Baby-Platypus-l.jpg)

**Comment by csdodd** [comment]
I was about to leave an issue for the same thing. The latest version of libjingle_peerconnection out on Maven is 7113; would it be possible to get a newer version deployed?

**Comment by aaalaniz** [comment]
Thanks for the encouragement everyone. I know it's been a while since we've updated the artifacts. I will post some new ones soon.

**Comment by aaalaniz** [comment]
@growlsworth @csdodd http://tech.pristine.io/automated-webrtc-building/

**Comment by growlsworth** [comment]
Boss. :+1:
