### ISSUE TITLE
Finally got android compilation to work on Mac OS X Yosemite, webrtc version 8097

### ISSUE THREAD

**Issue by growlsworth** [pristineio/webrtc-build-scripts#50]
Whoo hoo! After a bunch of days of downloading and cursing I finally got it to compile. I wanted to document my issues and my solutions to you.

1. I updated the vagrant vm to `ubuntu/trusty64`. I kept seeing things about deprecated support and to move to trusty. Don't know in the end if it was necessary but I don't feel it was harmful.
* I had to change the `ANDROID_TOOLCHAINS` variable to `"$WEBRTC_ROOT/src/chromium/src/third_party/android_tools/ndk/toolchains"`
* I had to change the location of `envsetup.sh` to `$WEBRTC_ROOT/src/chromium/src/build/android/envsetup.sh`
* I added `--force` to `gclient sync`. Don't know if this made a difference.
* I have my partition set to `Mac OS Extended (Journaled)`. I needed to create a `Mac OS Extended (Case-sensitive, Journaled)` partition. I had a bunch of issues fetching webrtc. I would constantly get `you have unstaged changes` from `gclient`. It just couldn't complete. Whatever I tried, I continued to get unstaged changes. I couldn't do a `git checkout .` `git diff | git apply --reverse` `git stash` `git reset --hard origin/master` `git clean -df` `git commit -am "remove" && git reset --hard head^` . Tried an interactive checkout. Tried checking out files one by one from master. Files still had differences. Moving the entire directory to a case sensitive partition fixed this. Debugging this one sucked the most.
* I could not get hard links to work on the shared `/vagrant` folder. I would get this error:

        Downloading /vagrant/webrtc/src/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2
        tar: ./bin/ld.gold: Cannot hard link to `./bin/ld': Operation not permitted

  I tried https://github.com/gael-ian/vagrant-bindfs , http://serverfault.com/questions/501599/vagrant-synced-folders-and-vboxinternal2-sharedfoldersenablesymlinkscreate , https://github.com/mitchellh/vagrant/issues/713#issuecomment-4416384 , plus others I cannot remember. I eventually gave up on this one and moved it to a different folder in my vagrant box that was not the shared project directory. The issue went away. This means I changed the `PROJECT_ROOT` environment variable.
* Then, there were a lot of unmet dependencies. I dunno I just kinda winged it one by one until eventually I just took this list: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/Rm1nX_LFYTo and hoped it worked. I removed all the ttf stuff.
* I added

        create_directory_if_not_found "$ARCH_OUT"
        create_directory_if_not_found "$ARCH_OUT/$BUILD_TYPE"
  before `exec_ninja`: https://github.com/pristineio/webrtc-build-scripts/blob/master/android/build.sh#L222 . Don't know if it was necessary but I got issues about "Directory not found". This happened way before I solved these other issues so it might not be necessary.

vagrant version 1.7.2 (installed with [homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vagrant.rb))

Sorry this isn't a pull request. I didn't want to submit all my code changes in a PR. I felt it was important to at least document the issues I had. That way if other people run into problems then at least they'll see they're not the only one.

Here's an adorable baby koala.
![Baby Koala](http://www.zooborns.com/.a/6a010535647bf3970b015433dca41d970c-800wi)

**Comment by smithaaron** [comment]
Many thanks for taking the time to write this. I have been getting the same issues you describe in number 5 so I'm going to try a case sensitive partition now.

**Comment by smithaaron** [comment]
Woo hoo, it worked!

FYI, for step 7 I just ran chromium/src/build/install-build-deps-android.sh and that worked

**Comment by csdodd** [comment]
I'm going to try and follow these steps as well; but is there any chance you could post the output of the build scripts somewhere anyway?

**Comment by smithaaron** [comment]
Here you go https://www.dropbox.com/s/3v0ur1imp4nfl0w/libjingle_peerconnection_builds.zip?dl=0 Debug version built earlier today

**Comment by csdodd** [comment]
Thanks smithaaron for the builds - it helped. I had to eventually get the library building myself anyway and I managed it with the help of growlsworth. Seriously, you deserve a medal - I have no idea how much time I would have thrown away before realising I need a case sensitive file system.

The only thing I encountered was an error when running build_apprtc. One of the scripts was having trouble doing a 'git reset --hard HEAD', I resolved this by deleting the index.lock file that was referenced in the error message. I had to do this a couple times for different directories but it worked in the end.

As for point 7 I ran 'install_dependencies' you can get it to work by editing the function in build.sh as follows:
```
install_dependencies() {
    sudo apt-get -y install wget git gnupg flex bison gperf build-essential zip curl subversion pkg-config
    #Download the latest script to install the android dependencies for ubuntu
    curl -o install-build-deps.sh https://src.chromium.org/svn/trunk/src/build/install-build-deps.sh
    curl -o install-build-deps-android.sh https://src.chromium.org/svn/trunk/src/build/install-build-deps-android.sh
    #use bash (not dash which is default) to run the script
    sudo /bin/bash ./install-build-deps.sh
    sudo /bin/bash ./install-build-deps-android.sh
    #delete the file we just downloaded... not needed anymore
    rm install-build-deps.sh
    rm install-build-deps-android.sh
}
```

**Comment by almozavr** [comment]
> I could not get hard links to work on the shared /vagrant folder.
 
`type: nfs` worked for me, as [docs say](https://docs.vagrantup.com/v2/synced-folders/nfs.html)
But, [bindfs](https://github.com/gael-ian/vagrant-bindfs) failed, so all I needed on Virtualbox 4.3.22 and vagrant 1.7.2 is to add:
```
config.vm.network "private_network", ip: "192.168.50.4"
config.vm.synced_folder ".", "/vagrant", type: :nfs
```

**Comment by almozavr** [comment]
Another problem was 
`/vagrant/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip: '/vagrant/webrtc/src/out_android_armeabi_v7a/Debug/libjingle_peerconnection_so.so': No such file`

Resolution: edit correct path for *so.so file like this:
`$STRIP -o $ARCH_JNI/libjingle_peerconnection_so.so $WEBRTC_ROOT/src/$ARCH_OUT/$BUILD_TYPE/lib/libjingle_peerconnection_so.so -s`
