### ISSUE TITLE
build_webrtc goes on forever

### ISSUE THREAD

**Issue by rishabhp** [pristineio/webrtc-build-scripts#54]
I've tried to follow the `README.md` guide that you guys have on Mac Yosemite and Ubuntu 14.04. After executing `build_apprtc` I see such messages:

```bash
[3:20:19]   src/third_party/android_tools
[3:20:29] Still working on:
[3:20:29]   src/third_party/android_tools
[3:20:39] Still working on:
[3:20:39]   src/third_party/android_tools
[3:20:49] Still working on:
[3:20:49]   src/third_party/android_tools
[3:20:59] Still working on:
[3:20:59]   src/third_party/android_tools
[3:21:09] Still working on:
[3:21:09]   src/third_party/android_tools
[3:21:19] Still working on:
[3:21:19]   src/third_party/android_tools
[3:21:29] Still working on:
[3:21:29]   src/third_party/android_tools
[3:21:39] Still working on:
[3:21:39]   src/third_party/android_tools
[3:21:49] Still working on:
```

That goes on forever and is never done. Am I missing something?

**Comment by ArikYa** [comment]
That is normal behavior. WebRTC is pulling about 6GB of data, so depending on your internet connection, it is going to take a while. Just be patient

**Comment by rishabhp** [comment]
Alrighty, let's see :(

**Comment by rishabhp** [comment]
Just for the records, if the internet connection drops while the scripts are downloading something, the entire process will fail and restart (that's what I noticed in my case) where it'll delete I think almost everything downloaded and restart the downloads. In this case the process probably will never end.

So a good internet connection that doesn't disconnects for even a second is very important. After probably 3 tries the process finally halted after 2hours (although with an error, for which I'll open a new issue).

**Comment by rishabhp** [comment]
@ArikYa I was just thinking when on Mac instead of installing a VM with Ubuntu, I could just purchase a VPS and go through the entire build process on that no? Since VPS's will have a much better (and faster) internet connection as well as dedicated hardware (enough RAM/CPU) just for the job.

The build process is purely CLI based (no GUI) involved so a remote server (from digitalocean, amazon, linode, etc.) might be a good environment to build. What say ?

**Comment by ArikYa** [comment]
You can certainly build these on any Ubuntu box, on your on machine or somewhere in the cloud.
I'm surprised to hear that if the download fails mid-way, it pulls everything from scratch. Everything is SVN/Git, so it should go back to the failure point.

**Comment by rishabhp** [comment]
Even I was surprised to observe that. How did I observe ? I kept a check on the size of the `webrtc-build-scripts` folder with `du -hsm webrtc-build-scripts`. Once I noticed it went up to 2000-3000 mb and then came back to 201 or something. The other time it I noticed 6.5gb and then upto 10gb then back to 6.5gb.

Given that the output is something like "working on src" for a few hours I'm not exactly sure what happens behind the scenes nor have I looked into the source files. What I observed could probably mean something else, but the thing is you need to have a good internet connection and I think a linux server in the cloud is the best bet (at least in my country heh).

**Comment by deano2390** [comment]
I like to run `nload` in a separate terminal window to give myself some reassurance that something is actually happening!
