### ISSUE TITLE
Build AppRTCDemo

### ISSUE THREAD

**Issue by gitbase** [pristineio/webrtc-build-scripts#56]
Hi,

I was able to follow the instructions from README.md and then I generated some so and jar files. But I've seen this - http://andrii.sergiienko.me/?go=all/building-webrtc-demo-for-android/ - and I think it shows us how to build an AppRTCDemo that works with http://apprtc.appspot.com/ I think.

So how can I build the same demo ? In that article it uses some ninja command. Any help would be useful!

Regards

**Comment by smithaaron** [comment]
I just created a project using the code from https://code.google.com/p/webrtc/source/browse/#svn%2Ftrunk%2Ftalk%2Fexamples%2Fandroid and dropped in the jar and so files that I'd built.

**Comment by ArikYa** [comment]
Running the script with build_apprtc builds the libraries and the Android demo application.

**Comment by gitbase** [comment]
@smithaaron ok

@ArikYa libraries are built but where is the Android demo application ? These are the build paths/lists of files:

```bash
$ pwd
/home/gitbase/webrtc-build-scripts/android/webrtc
$ ls
libjingle_peerconnection_builds  src
$ ls libjingle_peerconnection_builds/Release/
8148.zip  jniLibs/  libs/     res/      
$ ls libjingle_peerconnection_builds/Release/jniLibs/
armeabi_v7a  x86  x86_64
$ ls libjingle_peerconnection_builds/Release/libs/
libjingle_peerconnection.jar
$ ls libjingle_peerconnection_builds/Release/res/
```

**Comment by ArikYa** [comment]
look for an .apk file in "src/out_android_armeabi_v7a/Release"

**Comment by gitbase** [comment]
@ArikYa ah got it thanks! As for the source, is it also there somewhere or I have to clone from the google code URL pointed by @smithaaron ?

**Comment by ArikYa** [comment]
it's there under "src/talk/examples/android

**Comment by gitbase** [comment]
Thanks @ArikYa
