### ISSUE TITLE
Crash after enabling RTCVideoTrack

### ISSUE THREAD

**Issue by josipbernat** [pristineio/webrtc-build-scripts#57]
Hi,

Recently I've used this build script for creating iOS webRTC framework and then I decided to use your library through Cocoapods. Problem is that app crashes each time after I enable RTCVideoTrack (maybe a second later):

[videoTrack setEnabled:!mute]; //mute is some BOOL

I have this call stack, hope it can help.
![untitled](https://cloud.githubusercontent.com/assets/2537227/5919450/39907fd2-a634-11e4-8960-9940ae45b5fd.png)

**Comment by ArikYa** [comment]
Thank you for using our scripts. The code itself is maintained by Google's WebRTC team, the right place for their issue tracker is https://code.google.com/p/webrtc/issues/list. Your issue might be related to this: https://code.google.com/p/webrtc/issues/detail?id=4227

**Comment by josipbernat** [comment]
Sure I'll check there. Thanks.

**Comment by ArikYa** [comment]
@josipbernat Were you able to get this working? Anything else we can help with?

**Comment by josipbernat** [comment]
Hi, I'm using older version of the library for now. Thanks for your help :)
