### ISSUE TITLE
Building apprtc fails: revision 8353

### ISSUE THREAD

**Issue by i68040** [pristineio/webrtc-build-scripts#63]
Hi,

I'm trying to build webrtc for android using these commands:
	get_webrtc
	build_apprtc
	export WEBRTC_ARCH=armv7 #or armv8, x86, or x86_64
	prepare_gyp_defines && execute_build

** The zip file that is generated is less than 918 bytes and has a few empty folders in it.

I'm getting this message which includes an error:
=========================================
In file included from ../../webrtc/modules/audio_device/audio_device_impl.cc:28:0:
../../webrtc/modules/audio_device/android/audio_device_template.h: In instantiation of 'webrtc::AudioDeviceTemplate<InputType, OutputType>::AudioDeviceTemplate(int32_t) [with InputType = webrtc::OpenSlesInput; OutputType = webrtc::OpenSlesOutput; int32_t = int]':
../../webrtc/modules/audio_device/audio_device_impl.cc:280:85:   required from here
../../webrtc/modules/audio_device/android/audio_device_template.h:40:16: error: no matching function for call to 'webrtc::OpenSlesInput::OpenSlesInput()'
         input_() {
                ^
../../webrtc/modules/audio_device/android/audio_device_template.h:40:16: note: candidate is:
In file included from ../../webrtc/modules/audio_device/audio_device_impl.cc:31:0:
../../webrtc/modules/audio_device/android/opensles_input.h:38:3: note: webrtc::OpenSlesInput::OpenSlesInput(int32_t, webrtc::PlayoutDelayProvider*)
   OpenSlesInput(const int32_t id, PlayoutDelayProvider* delay_provider);
   ^
../../webrtc/modules/audio_device/android/opensles_input.h:38:3: note:   candidate expects 2 arguments, 0 provided
[8/157] CXX obj/webrtc/modules/audio_device/android/audio_device.opensles_input.o
ninja: build stopped: subcommand failed.
Copy JAR File
cp: cannot stat ‘/Repos/webrtc-build-scripts/android/webrtc/src/out_android_armeabi_v7a/Release/libjingle_peerconnection.jar’: No such file or directory
/Repos/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip: '/Repos/webrtc-build-scripts/android/webrtc/src/out_android_armeabi_v7a/Release/libjingle_peerconnection_so.so': No such file
  adding: libs/ (stored 0%)
  adding: res/ (stored 0%)
  adding: jniLibs/ (stored 0%)
  adding: jniLibs/x86/ (stored 0%)
  adding: jniLibs/armeabi_v7a/ (stored 0%)
  adding: jniLibs/x86_64/ (stored 0%)
Release build for apprtc complete for revision 8353

**Comment by i68040** [comment]
Ok, looks like this is in part due to this issue: https://code.google.com/p/webrtc/issues/detail?id=4293

I can 'build' without errors after I make the suggested source changes, but I only see empty folders in the jniLibs directory of the zip file. Hope I'm just missing something simple.

**Comment by almozavr** [comment]
the same as @i68040 :(

**Comment by almozavr** [comment]
@i68040 see my comments for your issue: https://github.com/pristineio/webrtc-build-scripts/issues/50#issuecomment-74234350

**Comment by almozavr** [comment]
@i68040 seems like to be fixed https://code.google.com/p/webrtc/source/detail?r=8360

**Comment by i68040** [comment]
Yes, it works for me now. I'd close this but my laptop gave me a BSOD‎ and I'm recovering from backups.                                                                                                                                                                                                                                                                                                                                                     From: Aleksey MalevaniySent: Saturday, February 14, 2015 08:59To: pristineio/webrtc-build-scriptsReply To: pristineio/webrtc-build-scriptsCc: Rion CarterSubject: Re: [webrtc-build-scripts] Building apprtc fails: revision 8353 (#63)@i68040 seems like to be fixed https://code.google.com/p/webrtc/source/detail?r=8360

—Reply to this email directly or view it on GitHub.

**Comment by ArikYa** [comment]
@i68040 Can we close this issue?

**Comment by i68040** [comment]
Yes please. I apologize if that wasn't clear from my last reply.                                                                                                                                                                                                                From: ArikYaSent: Wednesday, February 18, 2015 11:59To: pristineio/webrtc-build-scriptsReply To: pristineio/webrtc-build-scriptsCc: Rion CarterSubject: Re: [webrtc-build-scripts] Building apprtc fails: revision 8353 (#63)@i68040 Can we close this issue?

—Reply to this email directly or view it on GitHub.
