### ISSUE TITLE
Android Maven artifact support

### ISSUE THREAD

**Issue by tomfisher** [pristineio/webrtc-build-scripts#68]
Like Cocoapods, an Android Maven artifact would be extremely convenient since most of users just need the built jars.

**Comment by tomfisher** [comment]
Sorry, I found it. But it seems that outdated for a while.

**Comment by thebehera** [comment]
It's out of date but we are working on a clean way of keeping it up to
date.  Can't drop any timelines just yet but I will close the issue once it
works

**Comment by tomfisher** [comment]
Thanks :)

**Comment by aaalaniz** [comment]
@tomfisher http://tech.pristine.io/automated-webrtc-building/

**Comment by tomfisher** [comment]
You guys are so great!! Thanks a lot.
