### ISSUE TITLE
Why I'm still having this log on building native library? "Still working on:"

### ISSUE THREAD

**Issue by mejiamariano** [pristineio/webrtc-build-scripts#71]
________ running '/usr/bin/python -u src/sync_chromium.py --target-revision b0c3ed39916e25bed2900b653974672a39fcb254' in '/Users/username/Documents/github-repo/blumr-ios64/webrtc-build-scripts/ios/webrtc'
Running "gclient sync --force --revision src@b0c3ed39916e25bed2900b653974672a39fcb254 --gclientfile .gclient.tmp --delete_unversioned_trees --reset --upstream --deps=ios,mac" in /Users/username/Documents/github-repo/blumr-ios64/webrtc-build-scripts/ios/webrtc/src/chromium
[0:01:00] Still working on:
[0:01:00]   src
[0:01:10] Still working on:
[0:01:10]   src

**Comment by ArikYa** [comment]
The process downloads about 12GB of source code. This can take a few hours, so you;ll have to be patience till it is done

**Comment by mejiamariano** [comment]
@ArikYa, had you tested the armv7 and arm64?

**Comment by mejiamariano** [comment]
@ArikYa, thank you for answer. I had now the version for 64bit and the key is patience.
