### ISSUE TITLE
What's the best Way to apply Patches

### ISSUE THREAD

**Issue by anagromataf** [pristineio/webrtc-build-scripts#73]
I'm using libWebRTC in a project, where I need to make some small changes to the Objective-C wrapper. I would like to do the change locally in the build step as a patch (and submit it later to the official repo). What is the best way to include this automatically in the build process?

**Comment by aaalaniz** [comment]
Fork our [WebRTC Mirror](https://github.com/pristineio/webrtc-mirror) and make your changes in a branch. When you are done push those changes to the remote branch then you can change the url the build scripts use to build with the environment variable USER_WEBRTC_URL.

Assuming you forked the webrtc mirror and made changes in a branch called 'objc-wrapper-changes' your USER_WEBRTC_URL variable would be as follows:

```
export USER_WEBRTC_URL=ssh://git@github.com:anagromataf/webrtc-mirror.git@origin/objc-wrapper-changes
```

Set that before the build and gclient will pull down the source in that branch to build. Note that you might want to start from scratch as sometimes gclient will complain when going from svn to git.

Hope that helps!
