### ISSUE TITLE
Need help on building libjingle for android : still working on:

### ISSUE THREAD

**Issue by mejiamariano** [pristineio/webrtc-build-scripts#75]
Hi! I'm using mac for building android library, btw I had a successful building for iOS version with r8509. 
Here's what I did the following:
- go to my previous folder /android
- run vagrant up and ssh
- git clone https://github.com/pristineio/webrtc-build-scripts.git
- go to webrtc-build-scripts
- run source android/build.sh
- run get_webrtc 8509
- run build_apprtc

But, I'm stucked with this line:
[5:34:49] Still working on:
[5:34:49]   src/third_party/android_tools

**Comment by aaalaniz** [comment]
This is not an issue. You are downloading a lot of files. It could take hours to finish.
