### ISSUE TITLE
Build iOS with BoringSSL to support Firefox 38+

### ISSUE THREAD

**Issue by bruun** [pristineio/webrtc-build-scripts#76]
Firefox 38 [will require Perfect Forward Secrecy](https://hacks.mozilla.org/2015/02/webrtc-requires-perfect-forward-secrecy-pfs-starting-in-firefox-38/) for DTLS. The current iOS library is built using the standard SSL library (NSS) which doesn't support PFS. The guys at &yet have verified that building with the OpenSSL fork BoringSSL (which Chromium has moved to, iirc) solves the problem with Firefox 38 interopability.

This should be a small matter of adding `use_openssl=1` to the `GYP_DEFINES` in `build.sh`.

**Comment by ArikYa** [comment]
see here: https://code.google.com/p/webrtc/issues/detail?id=3605, it is still a work in progress

**Comment by bruun** [comment]
How about going from NSS to OpenSSL for now? It should solve the Firefox 38 problem according to those who have tried it (I have not built it myself, so I haven't verified it).

**Comment by bruun** [comment]
The discussion on the WebRTC issue above seems to go in the direction "switch to BoringSSL by default". Firefox 38 release is closing in quickly (1 month), and we soon need to start building WebRTC ourselves if the Pod doesn't switch to BoringSSL. The Pod is extremely convenient for us, so we'd love to avoid switching away from it.

**Comment by thebehera** [comment]
Started a jenkins build now to build the latest ios build that includes boringssl

https://github.com/pristineio/webrtc-mirror/commit/7d89f80fd49c734c34374cdb2b618c48befcc3f1

**Comment by thebehera** [comment]
should be finished in an hour or 2

**Comment by thebehera** [comment]
9013 is available on cocoapods 
https://github.com/CocoaPods/Specs/commit/eebfe7871e5374fd3e784dd756911a3af8bd216c

**Comment by bruun** [comment]
Thanks, I've verifies that it works on device! It seems the simulator binary doesn't build properly anymore, I get missing symbols in 9014. Maybe related?
