### ISSUE TITLE
Android build for arm64 not working

### ISSUE THREAD

**Issue by tercanfurkan** [pristineio/webrtc-build-scripts#78]
Android arm64 build is commented out and there is a note that the application can not yet build for arm64 successfully. Is this fix near in the roadmap?

https://github.com/pristineio/webrtc-build-scripts/blob/master/android/build.sh#L293
```bash
    # Uncomment once the application can successfully build for arm64
    #export WEBRTC_ARCH=armv8
    #prepare_gyp_defines &&
    #execute_build
```

**Comment by thebehera** [comment]
Originally ARM64 was slower than ARM32 because libvpx at the time did not have all the 64 bit arm instructions added. Now there shouldn't be an issue. Will uncomment and update. thanks for the ping
