### ISSUE TITLE
WebRTC SVN Repo is no longer valid

### ISSUE THREAD

**Issue by paynerc** [pristineio/webrtc-build-scripts#83]
Today when I attempted to pull the code, I was greeted with and empty directory, sans the README which stated:

> You're looking at the now retired Subversion repository for WebRTC.
>
> Please refer to http://www.webrtc.org/ for the location of the source code.

Has anybody started working on altering the scripts to pull from their git repo instead of svn? Looking through the build.sh script it appears that the main issue here will be that the svn revision number was used in a bunch of places.

Thoughts?

**Comment by paynerc** [comment]
Looks like this was as of yesterday morning:

> ------------------------------------------------------------------------
> r8849 | kjellander@webrtc.org | 2015-03-24 11:33:45 -0400 (Tue, 24 Mar 2015) | 4 lines
> Changed paths:
>    D /trunk/AUTHORS
>    D /trunk/BUILD.gn
>    D /trunk/COPYING
>    D /trunk/DEPS
>    D /trunk/LICENSE
>    D /trunk/LICENSE_THIRD_PARTY
>    D /trunk/OWNERS
>    D /trunk/PATENTS
>    D /trunk/PRESUBMIT.py
>    A /trunk/README
>    D /trunk/WATCHLISTS
>    D /trunk/all.gyp
>    D /trunk/check_root_dir.py
>    D /trunk/chromium
>    D /trunk/codereview.settings
>    D /trunk/data
>    D /trunk/drover.properties
>    D /trunk/libvpx.mk
>    D /trunk/license_template.txt
>    D /trunk/resources
>    D /trunk/setup_links.py
>    D /trunk/sync_chromium.py
>    D /trunk/talk
>    D /trunk/third_party
>    D /trunk/tools
>    D /trunk/webrtc
> 
> Removing all files and adding README.
> 
> The code has now moved to Git. See www.webrtc.org for details.

**Comment by aaalaniz** [comment]
I have updated the default url to point to the git repository. Let me know if you continue to have issues.
