### ISSUE TITLE
WebRTC code has moved from svn to git

### ISSUE THREAD

**Issue by csdodd** [pristineio/webrtc-build-scripts#84]
New code repo is here: https://chromium.googlesource.com/external/webrtc/+/master

These build scripts are using the old SVN repo which no longer receives changes.

**Comment by aaalaniz** [comment]
@csdodd This should be resolved in latest scripts

**Comment by aaalaniz** [comment]
https://github.com/pristineio/webrtc-build-scripts/blob/master/android/build.sh#L29
