### ISSUE TITLE
iOS - Subsequent pulls fail because the /src/talk/libjingle_examples.gyp file has been modified

### ISSUE THREAD

**Issue by paynerc** [pristineio/webrtc-build-scripts#86]
Building after a fresh checkout works fine. However, any subsequent attempts to pull the latest code or build using the dance scripts has the pull fail because we have manipulated /src/talk/libjingle_examples.gyp. The script needs to be smart enough to either force the git pull or revert the changed before pulling.

    Syncing projects: 100% ( 1/ 1) src
    
    src (ERROR)
    ----------------------------------------
    [0:00:00] Started.
    ----------------------------------------
    Error: 1>
    1> ____ src at refs/remotes/origin/master
    1> 	You have unstaged changes.
    1> 	Please commit, stash, or reset.

**Comment by puyide** [comment]
I have the same problem. You solve it?

**Comment by paynerc** [comment]
I haven't done anything with this as I have been evaluating another WebRTC library for iOS. When I get back to working with the Google Implementation I will see what I can figure out if it hasn't been fixed yet.

**Comment by paynerc** [comment]
Fixed above in PR #94.
