### ISSUE TITLE
"build_apprtc" not working

### ISSUE THREAD

**Issue by efecannn** [pristineio/webrtc-build-scripts#98]
Setting up build environment for Android
Export the base settings of GYP_DEFINES so we can define how we want to build
User has not specified any gyp defines so we proceed with default
ARMv7 with Neon Build
GYP_DEFINES=OS=android host_os=linux libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 enable_tracing=1 enable_android_opensl=0 OS=android
Run gclient hooks
Running depot tools as root is sad.
Build AppRTCDemo in Release (arch: armv7)
Running ninja
log: ninja version 0.1.3 initializing
log: magic group: gid=0 (root)
log: entering main loop
log: generating initial pid array..
log: now monitoring process activity

---------------------------
OS=Ubuntu

**Comment by aaalaniz** [comment]
can you provide the commands you are executing?

**Comment by efecannn** [comment]
fixed: Do not use root user.
