### ISSUE TITLE
Build Failing:  Error: Command download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-        gn -s src/buildtools/mac/gn.sha1 returned non-zero exit status

### ISSUE THREAD

**Issue by KCastiglione** [pristineio/webrtc-build-scripts#99]
webrtc-build-scripts git version:

       commit 4b791624af04b9f56fe7b9b44674a65a019339cb
       Merge: 7d64ae2 ffbea55
       Author: Rahul Behera <rahul@pristine.io>
       Date:   Tue Apr 28 13:28:35 2015 -0500

commands executed: 

     git clone https://github.com/pristineio/webrtc-build-scripts.git
     cd webrtc-build-scripts/
     source ios/build.sh 
     dance
     

webrtc git version

      commit b26198972c1fcb4aa7abaf3895b007e301e7d5dc
      Author: henrika <henrika@chromium.org>
      Date:   Mon May 18 16:49:16 2015 +0200
      
error output:

        ________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-        gn -s src/buildtools/win/gn.exe.sha1' in '/Users/live/pristine.io.webrtc/webrtc-build-scripts/ios/webrtc        /src/chromium'
        
        ________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium        -gn -s src/buildtools/mac/gn.sha1' in '/Users/live/pristine.io.webrtc/webrtc-build-scripts/ios/webrtc/        src/chromium'
        Error: Command download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-        gn -s src/buildtools/mac/gn.sha1 returned non-zero exit status 1 in /Users/live/pristine.io.webrtc/        webrtc-build-scripts/ios/webrtc/src/chromium
        File gs://chromium-gn/ca4020ac29579140e5731871f7b90e55b843e030 for src/buildtools/mac/gn does not exist.
        0> File gs://chromium-gn/ca4020ac29579140e5731871f7b90e55b843e030 for src/buildtools/mac/gn does not         exist, skipping.
        Error: Command /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.        app/Contents/MacOS/Python -u src/sync_chromium.py --target-revision         1b9c098a08e40114e44b6c1ec33ddf95c40b901d returned non-zero exit status 2 in /Users/live/pristine.io.        webrtc/webrtc-build-scripts/ios/webrtc
        Hook '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/        Contents/MacOS/Python -u src/sync_chromium.py --target-revision         1b9c098a08e40114e44b6c1ec33ddf95c40b901d' took 34.64 secs
        Running ninja
        ninja: Entering directory `out_ios_x86_64/Debug-iphonesimulator/'
        ninja: fatal: chdir to 'out_ios_x86_64/Debug-iphonesimulator/' - No such file or directory
        Running libtool
        error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool:         can't open file: /Users/live/pristine.io.webrtc/webrtc-build-scripts/ios/webrtc/src/out_ios_x86_64/Debug        -iphonesimulator/*.a (No such file or directory)
        fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/        lipo: can't open input file: /Users/live/pristine.io.webrtc/webrtc-build-scripts/ios/webrtc/        libjingle_peerconnection_builds/libWebRTC-9208-ios-armeabi_v7a-Debug.a (No such file or directory)
        Finished Dancing!
        live@MAC-2:~/pristine.io.webrtc/webrtc-build-scripts/ios/webrtc/src$

**Comment by Frank-HeFei** [comment]
i have up issue,waiting for answer

**Comment by ArikYa** [comment]
It seems to be a general WebRTC problem, please look here: https://groups.google.com/forum/#!topic/discuss-webrtc/Dt-GRIlLVe4

**Comment by KCastiglione** [comment]
@ArikYa I am not behind a proxy and none of the solutions in that link help also.

Can we please leave this opened till resolved.

**Comment by yusupprog** [comment]
same issue
